### ISSUE TITLE
Update to latest version of AsciidoctorJ

### ISSUE THREAD

**Issue by kidflash** [cryogen-project/cryogen-asciidoc#16]
Can we bump up the dependency to latest version of AsciidoctorJ - currently v2.5.3?

Thank you so much!

**Comment by yogthos** [comment]
No problem, just released out `0.3.4` with the latest Asciidoctorj.

**Comment by kidflash** [comment]
Thank you! My numbered and bulleted lists now work as intended from the current documentation. I'm very happy.
