### ISSUE TITLE
Asciidoc File Extension

### ISSUE THREAD

**Issue by gotwf** [cryogen-project/cryogen-asciidoc#6]
Greetings o/

It would be nice if Cyrogen could recognize/parse asciidoc files using the .adoc, asciidoc, and perhaps even .txt extensions.  

Per [Asciidoc Recommended Practices](https://asciidoctor.org/docs/asciidoc-recommended-practices/):

>AsciiDoc doesn’t care which extension you use. GitHub supports the extensions .asciidoc, .adoc and .asc.

  | We strongly recommend against using the .asc extension. The connection to AsciiDoc isn’t immediately obvious and it gets falsely identified as a PGP file on Linux.
-- | --

I would favor .adoc and .txt.

Thanks bunches o/

**Comment by lacarmen** [comment]
In order to support this [ext](https://github.com/cryogen-project/cryogen-asciidoc/blob/master/src/cryogen_asciidoc/core.clj#L18) would have to return multiple file extensions and [usages](https://github.com/cryogen-project/cryogen-core/blob/master/src/cryogen_core/io.clj#L53) of `ext` would have to be updated to handle that.

**Comment by gotwf** [comment]
Well then they'd best get on with it... ;-P

Just a lowly systems person and I don't code java, clojure, or anything else for that matter.  One of *the* greatest things about Cryogen that differentiate it from the sea of SSG's is it's Asciidoc support.  Folks are slowly but steadily getting clued into both its ease of use and superiority so mayhaps we'll see increased demand in such among SSG users.  Cryogen is  slick in this regard as it can leverage asciidoctor thru jruby.  I thought it might be good to bring the implementation into compliance with Best Recommendations.  No sweat though, cuz works fer' me as is.

For those intrigued by the search for enlightenment: [The Case for Asciidoc](https://asciidoctor.org/docs/asciidoc-vs-markdown/)

**Comment by lacarmen** [comment]
Just noting what would need to be done if someone wants to tackle it. :) 

Glad things are working for you!

**Comment by bombaywalla** [comment]
I'd like to contribute a PR for this.

Here's what I'm thinking.

- Change `cryogen-core.io/find-assets` to expect `ext` to be a set of strings.
- Change each implementation of `Markup` to return a set of strings for `ext`.
- Update the docs appropriately.
- Anything else?

If that is acceptable, I'll submit PRs to each of the impacted repos.
BTW, is there a way to submit a set of coordinated PRs to multiple repos?

**Comment by bombaywalla** [comment]
Turned out to be more involved than what I expected.
See PR number 146 on the `cryogen-core` repo.
That includes the full set of related PRs.
I guess the `cryogen` template repo should be updated to refer to the latest versions as well.

**Comment by gotwf** [comment]
I was happy to note cryogenweb docs 

>  the compiler will now look for files ending in any of the following extensions in the content/asc directory: .adoc, .ad, .asciidoc, .asc.

Alas... cryogen is now borked for me when I endeavor to do so.

Spews thusly:

><kvg@loon:~/Projects/GoodBooks/blog>% lein ring server
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
2020-11-11 09:58:42.082:INFO::main: Logging initialized @1312ms
loading module: AsciiDoc parser
Syntax error (IllegalArgumentException) compiling reify* at (cryogen_asciidoc/core.clj:16:3).
Can't define method not in interfaces: ext

Full report at:
/tmp/clojure-3045614592923664658.edn
Subprocess failed (exit code: 1)

Seem github is being lame and not allowing me to attach files, so, geronimo, here ya' go... it all its glory:

> cat clojure-3045614592923664658.edn
{:clojure.main/message
 "Syntax error (IllegalArgumentException) compiling reify* at (cryogen_asciidoc/core.clj:16:3).\nCan't define method not in interfaces: ext\n",
 :clojure.main/triage
 {:clojure.error/phase :compile-syntax-check,
  :clojure.error/line 16,
  :clojure.error/column 3,
  :clojure.error/source "core.clj",
  :clojure.error/symbol reify*,
  :clojure.error/path "cryogen_asciidoc/core.clj",
  :clojure.error/class java.lang.IllegalArgumentException,
  :clojure.error/cause "Can't define method not in interfaces: ext"},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message
    "Syntax error compiling reify* at (cryogen_asciidoc/core.clj:16:3).",
    :data
    {:clojure.error/phase :compile-syntax-check,
     :clojure.error/line 16,
     :clojure.error/column 3,
     :clojure.error/source "cryogen_asciidoc/core.clj",
     :clojure.error/symbol reify*},
    :at [clojure.lang.Compiler analyzeSeq "Compiler.java" 7115]}
   {:type java.lang.IllegalArgumentException,
    :message "Can't define method not in interfaces: ext",
    :at
    [clojure.lang.Compiler$NewInstanceMethod
     parse
     "Compiler.java"
     8529]}],
  :trace
  [[clojure.lang.Compiler$NewInstanceMethod parse "Compiler.java" 8529]
   [clojure.lang.Compiler$NewInstanceExpr build "Compiler.java" 8059]
   [clojure.lang.Compiler$NewInstanceExpr$ReifyParser
    parse
    "Compiler.java"
    7960]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7107]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7095]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler$BodyExpr$Parser parse "Compiler.java" 6120]
   [clojure.lang.Compiler$FnMethod parse "Compiler.java" 5467]
   [clojure.lang.Compiler$FnExpr parse "Compiler.java" 4029]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7105]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7095]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler access$300 "Compiler.java" 38]
   [clojure.lang.Compiler$DefExpr$Parser parse "Compiler.java" 596]
   [clojure.lang.Compiler analyzeSeq "Compiler.java" 7107]
   [clojure.lang.Compiler analyze "Compiler.java" 6789]
   [clojure.lang.Compiler analyze "Compiler.java" 6745]
   [clojure.lang.Compiler eval "Compiler.java" 7181]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.RT loadResourceScript "RT.java" 381]
   [clojure.lang.RT loadResourceScript "RT.java" 372]
   [clojure.lang.RT load "RT.java" 459]
   [clojure.lang.RT load "RT.java" 424]
   [clojure.core$load$fn__6839 invoke "core.clj" 6126]
   [clojure.core$load invokeStatic "core.clj" 6125]
   [clojure.core$load doInvoke "core.clj" 6109]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [clojure.core$load_one invokeStatic "core.clj" 5908]
   [clojure.core$load_one invoke "core.clj" 5903]
   [clojure.core$load_lib$fn__6780 invoke "core.clj" 5948]
   [clojure.core$load_lib invokeStatic "core.clj" 5947]
   [clojure.core$load_lib doInvoke "core.clj" 5928]
   [clojure.lang.RestFn applyTo "RestFn.java" 142]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$load_libs invokeStatic "core.clj" 5985]
   [clojure.core$load_libs doInvoke "core.clj" 5969]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$require invokeStatic "core.clj" 6007]
   [clojure.core$require doInvoke "core.clj" 6007]
   [clojure.lang.RestFn invoke "RestFn.java" 408]
   [cryogen_core.plugins$load_plugin invokeStatic "plugins.clj" 9]
   [cryogen_core.plugins$load_plugin invoke "plugins.clj" 6]
   [cryogen_core.plugins$load_plugins invokeStatic "plugins.clj" 15]
   [cryogen_core.plugins$load_plugins invoke "plugins.clj" 12]
   [cryogen.server$init invokeStatic "server.clj" 15]
   [cryogen.server$init invoke "server.clj" 14]
   [clojure.lang.Var invoke "Var.java" 380]
   [ring.server.standalone$serve invokeStatic "standalone.clj" 96]
   [ring.server.standalone$serve doInvoke "standalone.clj" 75]
   [clojure.lang.RestFn invoke "RestFn.java" 423]
   [ring.server.leiningen$serve invokeStatic "leiningen.clj" 19]
   [ring.server.leiningen$serve invoke "leiningen.clj" 16]
   [user$eval12537 invokeStatic "form-init2874568225127958887.clj" 1]
   [user$eval12537 invoke "form-init2874568225127958887.clj" 1]
   [clojure.lang.Compiler eval "Compiler.java" 7177]
   [clojure.lang.Compiler eval "Compiler.java" 7167]
   [clojure.lang.Compiler load "Compiler.java" 7636]
   [clojure.lang.Compiler loadFile "Compiler.java" 7574]
   [clojure.main$load_script invokeStatic "main.clj" 475]
   [clojure.main$init_opt invokeStatic "main.clj" 477]
   [clojure.main$init_opt invoke "main.clj" 477]
   [clojure.main$initialize invokeStatic "main.clj" 508]
   [clojure.main$null_opt invokeStatic "main.clj" 542]
   [clojure.main$null_opt invoke "main.clj" 539]
   [clojure.main$main invokeStatic "main.clj" 664]
   [clojure.main$main doInvoke "main.clj" 616]
   [clojure.lang.RestFn applyTo "RestFn.java" 137]
   [clojure.lang.Var applyTo "Var.java" 705]
   [clojure.main main "main.java" 40]],
  :cause "Can't define method not in interfaces: ext",
  :phase :compile-syntax-check}}

My project.clj:

> cat project.clj 
(defproject cryogen "0.1.0"
            :description "Simple static site generator"
            :url "https://github.com/lacarmen/cryogen"
            :license {:name "Eclipse Public License"
                      :url "http://www.eclipse.org/legal/epl-v10.html"}
            :dependencies [[org.clojure/clojure "1.10.1"]
                           [ring/ring-devel "1.8.2"]
                           [compojure "1.6.2"]
                           [ring-server "0.5.0"]
                           [cryogen-asciidoc "0.1.4"]
                           [cryogen-core "0.3.2"]]
            :plugins [[lein-ring "0.12.5"]]
            :main cryogen.core
            :ring {:init cryogen.server/init
                   :handler cryogen.server/handler})

**Comment by gotwf** [comment]
Cool that this was incorporated.  Threw me for a loop until I got the "0.3.3" version update.  Made the mistake of checking Carmen's docs rather than here first.

In any case, good on ya' whoever got this puppy done did and done. :+1:

**Comment by bombaywalla** [comment]
This was addressed in PR number 146 on the `cryogen-core` repo, and the related PRs on other repos.
So closing this issue.
